from django.db import models

# Create your models here.

class Khedut(models.Model):

    marquee_1 = models.TextField()
    marquee_2 = models.TextField()
    marquee_3 = models.TextField()
    marquee_4 = models.TextField()
    marquee_5 = models.TextField()
    khedut_main_image = models.ImageField(upload_to='pics')
    khedut_main_headline = models.TextField()
    khedut_main_readless = models.TextField()
    khedut_main_readmore = models.TextField()
    main_flag = models.BooleanField(default=False)
    khedut_body_card_image = models.ImageField(upload_to='pics')
    khedut_body_card_headline = models.TextField()
    khedut_body_card_readless = models.TextField()
    khedut_body_card_readmore = models.TextField()
    breaking_card_image = models.ImageField(upload_to='pics')
    breaking_card_headline = models.TextField()
    small_card_image = models.ImageField(upload_to='pics')
    small_card_headline = models.TextField()
    scroll_card_image = models.ImageField(upload_to='pics')
    scroll_card_desc = models.TextField()
    last_card_image = models.ImageField(upload_to='pics')
    last_card_headline = models.TextField()
    last_card_subline = models.TextField()

class Janvajevu(models.Model):

    marquee_1 = models.TextField()
    marquee_2 = models.TextField()
    marquee_3 = models.TextField()
    marquee_4 = models.TextField()
    marquee_5 = models.TextField()
    janvajevu_main_image = models.ImageField(upload_to='pics')
    janavjevu_main_headline = models.TextField()
    janvajevu_main_readless = models.TextField()
    janvajevu_main_readmore = models.TextField()
    main_flag= models.BooleanField(default=False)
    janvajevu_body_card_image = models.ImageField(upload_to='pics')
    janvajevu_body_card_headline = models.TextField()
    janvajevu_body_card_readless = models.TextField()
    janvajevu_body_card_readmore = models.TextField()
    breaking_card_image = models.ImageField(upload_to='pics')
    breaking_card_headline = models.TextField()
    small_card_image = models.ImageField(upload_to='pics')
    small_card_headline = models.TextField()
    scroll_card_image = models.ImageField(upload_to='pics')
    scroll_card_desc = models.TextField()
    last_card_image = models.ImageField(upload_to='pics')
    last_card_headline = models.TextField()
    last_card_subline = models.TextField()



class Lekh(models.Model):

    marquee_1 = models.TextField()
    marquee_2 = models.TextField()
    marquee_3 = models.TextField()
    marquee_4 = models.TextField()
    marquee_5 = models.TextField()
    lekh_main_image = models.ImageField(upload_to='pics')
    lekh_main_headline = models.TextField()
    lekh_main_readless = models.TextField()
    lekh_main_readmore = models.TextField()
    main_flag= models.BooleanField(default=False)
    lekh_body_card_image  = models.ImageField(upload_to='pics')
    lekh_body_card_headline = models.TextField()
    lekh_body_card_readless = models.TextField()
    lekh_body_card_readmore = models.TextField()
    breaking_card_image = models.ImageField(upload_to='pics')
    breaking_card_headline = models.TextField()
    small_card_image = models.ImageField(upload_to='pics')
    small_card_headline = models.TextField()
    scroll_card_image = models.ImageField(upload_to='pics')
    scroll_card_desc = models.TextField()
    last_card_image = models.ImageField(upload_to='pics')
    last_card_headline = models.TextField()
    last_card_subline = models.TextField()


class Rajkaran(models.Model):

    marquee_1= models.TextField()
    marquee_2 = models.TextField()
    marquee_3 = models.TextField()
    marquee_4 = models.TextField()
    marquee_5 = models.TextField()
    rajkaran_main_image = models.ImageField(upload_to='pics')
    rajkaran_main_headline = models.TextField()
    rajkaran_main_readless = models.TextField()
    rajkaran_main_readmore = models.TextField()
    main_flag = models.BooleanField(default=False)
    rajkaran_body_card_image = models.ImageField(upload_to='pics')
    rajkaran_body_card_headline = models.TextField()
    rajkaran_body_card_readless = models.TextField()
    rajkaran_body_card_readmore = models.TextField()
    breaking_card_image = models.ImageField(upload_to='pics')
    breaking_card_headline= models.TextField()
    small_card_image = models.ImageField(upload_to='pics')
    small_card_headline = models.TextField()
    scroll_card_image = models.ImageField(upload_to='pics')
    scroll_card_desc= models.TextField()
    last_card_image = models.ImageField(upload_to='pics')
    last_card_headline = models.TextField()
    last_card_subline = models.TextField()


class Dharmik(models.Model):

    marquee_1 = models.TextField()
    marquee_2 = models.TextField()
    marquee_3 = models.TextField()
    marquee_4 = models.TextField()
    marquee_5 = models.TextField()
    dharmik_main_image = models.ImageField(upload_to='pics')
    dharmik_main_headline = models.TextField()
    dharmik_main_readless = models.TextField()
    dharmik_main_readmore = models.TextField()
    main_flag= models.BooleanField(default=False)
    dharmik_body_card_image = models.ImageField(upload_to='pics')
    dharmik_body_card_headline = models.TextField()
    dharmik_body_card_readless = models.TextField()
    dharmik_body_card_readmore = models.TextField()
    breaking_card_image = models.ImageField(upload_to='pics')
    breaking_card_headline = models.TextField()
    small_card_image = models.ImageField(upload_to='pics')
    small_card_headline = models.TextField()
    scroll_card_image = models.ImageField(upload_to='pics')
    scroll_card_desc = models.TextField()
    last_card_image = models.ImageField(upload_to='pics')
    last_card_headline = models.TextField()
    last_card_subline = models.TextField()

class Swasthya(models.Model):

    marquee_1= models.TextField()
    marquee_2 = models.TextField()
    marquee_3 = models.TextField()
    marquee_4 = models.TextField()
    marquee_5 = models.TextField()
    swasthya_main_image = models.ImageField(upload_to='pics')
    swasthya_main_headline = models.TextField()
    swasthya_main_readless = models.TextField()
    swasthya_main_readmore = models.TextField()
    main_flag= models.BooleanField(default=False)
    swasthya_body_card_image = models.ImageField(upload_to='pics')
    swasthya_body_card_headline = models.TextField()
    swasthya_body_card_readless = models.TextField()
    swasthya_body_card_readmore = models.TextField()
    breaking_card_image = models.ImageField(upload_to='pics')
    breaking_card_headline = models.TextField()
    small_card_image = models.ImageField(upload_to='pics')
    small_card_headline = models.TextField()
    scroll_card_image = models.ImageField(upload_to='pics')
    scroll_card_desc = models.TextField()
    last_card_image = models.ImageField(upload_to='pics')
    last_card_headline = models.TextField()
    last_card_subline = models.TextField()

class Samachar(models.Model):

    marquee_1 = models.TextField()
    marquee_2 = models.TextField()
    marquee_3 = models.TextField()
    marquee_4 = models.TextField()
    marquee_5 = models.TextField()
    samachar_main_image = models.ImageField(upload_to='pics')
    samachar_main_headline = models.TextField()
    samachar_main_readless = models.TextField()
    samachar_main_readmore = models.TextField()
    main_flag= models.BooleanField(default=False)
    samachar_body_card_image = models.ImageField(upload_to='pics')
    samachar_body_card_headline = models.TextField()
    samachar_body_card_readless = models.TextField()
    samachar_body_card_readmore = models.TextField()
    breaking_card_image = models.ImageField(upload_to='pics')
    breaking_card_headline = models.TextField()
    small_card_image = models.ImageField(upload_to='pics')
    small_card_headline = models.TextField()
    scroll_card_image = models.ImageField(upload_to='pics')
    scroll_card_desc = models.TextField()
    last_card_image = models.ImageField(upload_to='pics')
    last_card_headline = models.TextField()
    last_card_subline = models.TextField()

class About(models.Model):

    marquee_1 = models.TextField()
    marquee_2 = models.TextField()
    marquee_3 = models.TextField()
    marquee_4 = models.TextField()
    marquee_5 = models.TextField()