# Generated by Django 3.0.5 on 2020-06-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='main_flag',
            field=models.BooleanField(default=False),
        ),
    ]
